### ISSUE TITLE
Hide pkg versions with auth

### ISSUE THREAD

**Issue by jeffscrum** [guackamolly/zero-monitor#23]
For security reasons it will be nice to show packages and versions after auth.

**Comment by freitzzz** [comment]
Hi Jeff! Thanks for the feedback, I actually thought that revealing system packages isn’t such a risk, but now that I think of it, it poses a security risk because you may have vulnerable packages and that gives advantages to an attacker.

For now I will release a new version with packages disabled for guests, but will start thinking how to include a way to configure which pages can be viewed by guests and what not.
